#!/usr/bin/env sh
set -eu
exec 2>&1

DAEMON=/usr/sbin/php-fpm7

test -x ${DAEMON} || (echo 'php-fpm has not installed.' && exit 1)
${DAEMON} --test || (echo 'php-fpm config has error.' && exit 1)

exec ${DAEMON} --nodaemonize --fpm-config /etc/php7/php-fpm.conf
